STATE_FILE_NAME = "state.pkl"

ACCOUNT_PAGE_SCREENSHOT_PATH = "screenshots/account_page.png"
BEFORE_TIMEOUT_SCREENSHOT_PATH = "screenshots/before_timeout.png"
BEFORE_ERROR_SCREENSHOT_PATH = "screenshots/before_error.png"
LOGIN_URL = "https://ing.ingdirect.es/app-login/"
MAIN_URL = "https://ing.ingdirect.es/pfm/#overall-position"
IS_ACTIVATED = "Encendida"
ACCOUNT_DELIMITER = "Cuenta"
CARD_DELIMITER = "Tarjeta"
